name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add permissions for GitHub Pages deployment
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install pymdown-extensions
        
      - name: Build documentation
        run: |
          mkdocs build
          
      - name: Debug documentation build
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Current directory contents:"
          ls -la
          echo "Site directory contents (if exists):"
          if [ -d "site" ]; then
            ls -la site/
          else
            echo "Site directory not found in root"
          fi
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
